export const orders = [
  {
    date: "23-05-2025",
    orderId: "V-545454",
    dealership: "AK Motors",
    customerName: "Aman upadhyay",
    serviceType: "General Service",
    mode: "Online",
    status: "In progress",
  },
  {
    date: "23-05-2025",
    orderId: "V-545454",
    dealership: "AK Motors",
    customerName: "Aman upadhyay",
    serviceType: "General Service",
    mode: "Offline",
    status: "In progress",
  },
  {
    date: "23-05-2025",
    orderId: "V-545454",
    dealership: "AK Motors",
    customerName: "Aman upadhyay",
    serviceType: "General Service",
    mode: "Offline",
    status: "Completed",
  },
  {
    date: "23-05-2025",
    orderId: "V-545454",
    dealership: "AK Motors",
    customerName: "Aman upadhyay",
    serviceType: "General Service",
    mode: "Offline",
    status: "In progress",
  },
  {
    date: "23-05-2025",
    orderId: "V-545454",
    dealership: "AK Motors",
    customerName: "Aman upadhyay",
    serviceType: "General Service",
    mode: "Offline",
    status: "In progress",
  },
  {
    date: "23-05-2025",
    orderId: "V-545454",
    dealership: "AK Motors",
    customerName: "Aman upadhyay",
    serviceType: "General Service",
    mode: "Online",
    status: "In progress",
  },
  {
    date: "23-05-2025",
    orderId: "V-545454",
    dealership: "AK Motors",
    customerName: "Aman upadhyay",
    serviceType: "General Service",
    mode: "Online",
    status: "Completed",
  },
];
